/* =====================================================
   PAPO DE BOLA - API Layer
   Reads cached JSON files generated by server-side script
   Falls back to direct API calls if cache unavailable
   ===================================================== */

const API = {
    CACHE_BASE: window.location.origin + '/cache',

    // Read from cached JSON file
    async fetchCache(filename) {
        try {
            const response = await fetch(`${this.CACHE_BASE}/${filename}?_=${Date.now()}`);
            if (!response.ok) return null;
            const data = await response.json();
            return data;
        } catch (e) {
            console.warn(`Cache miss: ${filename}`, e.message);
            return null;
        }
    },

    // Direct API call (fallback, uses quota)
    async fetchAPI(endpoint) {
        if (!CONFIG.API_KEY) return null;

        try {
            const response = await fetch(`${CONFIG.API_BASE}/${endpoint}`, {
                method: 'GET',
                headers: {
                    'x-rapidapi-key': CONFIG.API_KEY,
                    'x-rapidapi-host': CONFIG.API_HOST,
                },
            });
            if (response.status === 429) {
                console.warn('API quota exceeded');
                return null;
            }
            if (!response.ok) return null;
            return await response.json();
        } catch (e) {
            console.error('API error:', e);
            return null;
        }
    },

    // ==================== LIVE ====================
    async getLiveEvents() {
        // Try cache first
        const cached = await this.fetchCache('live.json');
        if (cached?.events) return cached.events;

        // Fallback to direct API
        const data = await this.fetchAPI('sport/football/events/live');
        return data?.events || [];
    },

    // ==================== TODAY'S MATCHES ====================
    async getTodayEvents() {
        const cached = await this.fetchCache('today.json');
        if (cached?.events) return cached.events;

        const today = new Date().toISOString().split('T')[0];
        const [y, m, d] = today.split('-');
        const data = await this.fetchAPI(`sport/football/scheduled-events/${y}-${m}-${d}`);
        return data?.events || [];
    },

    // ==================== TOMORROW'S MATCHES ====================
    async getTomorrowEvents() {
        const cached = await this.fetchCache('tomorrow.json');
        if (cached?.events) return cached.events;

        const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
        const [y, m, d] = tomorrow.split('-');
        const data = await this.fetchAPI(`sport/football/scheduled-events/${y}-${m}-${d}`);
        return data?.events || [];
    },

    // ==================== STANDINGS ====================
    async getStandings(tournamentId, seasonId) {
        // Use cached Brasileirão standings
        if (tournamentId === 325) {
            const cached = await this.fetchCache('standings_brasileirao.json');
            if (cached?.standings) return cached.standings;
        }

        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/season/${seasonId}/standings/total`);
        return data?.standings || null;
    },

    // ==================== STATISTICS ====================
    async getStatistics(tournamentId, seasonId) {
        if (tournamentId === 325) {
            const cached = await this.fetchCache('stats_brasileirao.json');
            if (cached?.results) return cached.results;
        }

        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/season/${seasonId}/statistics`);
        return data?.results || null;
    },

    // ==================== TOURNAMENT EVENTS ====================
    async getTournamentLastEvents(tournamentId, seasonId, page = 0) {
        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/season/${seasonId}/events/last/${page}`);
        return data?.events || [];
    },

    async getTournamentNextEvents(tournamentId, seasonId, page = 0) {
        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/season/${seasonId}/events/next/${page}`);
        return data?.events || [];
    },

    // ==================== TOURNAMENT SEASONS ====================
    async getTournamentSeasons(tournamentId) {
        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/seasons`);
        return data?.seasons || [];
    },

    // ==================== TOURNAMENT INFO ====================
    async getTournamentInfo(tournamentId, seasonId) {
        const data = await this.fetchAPI(`unique-tournament/${tournamentId}/season/${seasonId}/info`);
        return data?.info || null;
    },

    // ==================== CACHE META ====================
    async getCacheMeta() {
        return await this.fetchCache('meta.json');
    },

    // ==================== NORMALIZE EVENT ====================
    normalizeEvent(event) {
        const status = this.mapStatus(event.status);
        const tournamentId = event.tournament?.uniqueTournament?.id;
        const startTime = event.startTimestamp ? new Date(event.startTimestamp * 1000) : null;

        return {
            id: `api_${event.id}`,
            apiId: event.id,
            league: event.tournament?.uniqueTournament?.name || event.tournament?.name || 'Desconhecido',
            leagueId: tournamentId,
            country: event.tournament?.category?.name,
            homeTeam: event.homeTeam?.name || 'TBD',
            awayTeam: event.awayTeam?.name || 'TBD',
            homeScore: event.homeScore?.current ?? event.homeScore?.display ?? 0,
            awayScore: event.awayScore?.current ?? event.awayScore?.display ?? 0,
            homeLogo: event.homeTeam?.id ? `/img/team/${event.homeTeam.id}/image` : null,
            awayLogo: event.awayTeam?.id ? `/img/team/${event.awayTeam.id}/image` : null,
            time: startTime ? startTime.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '',
            date: startTime ? startTime.toISOString().split('T')[0] : '',
            status: status.type,
            statusText: status.text,
            minute: event.statusTime?.played ? `${event.statusTime.played}'` : (typeof translateStatus === 'function' ? translateStatus(event.status?.description || '') : (event.status?.description || '')),
            embeds: [],
            isManual: false,
            category: getLeagueCategory(tournamentId),
        };
    },

    mapStatus(status) {
        if (!status) return { type: 'scheduled', text: '' };
        const type = status.type;
        const code = status.code;
        const desc = status.description;

        if (type === 'inprogress') {
            if (code === 6) return { type: 'live', text: '1º Tempo' };
            if (code === 7) return { type: 'live', text: '2º Tempo' };
            if (code === 41) return { type: 'live', text: 'Prorrogação' };
            return { type: 'live', text: desc || 'AO VIVO' };
        }
        if (type === 'finished') {
            if (code === 120) return { type: 'finished', text: 'AP' };
            if (code === 110) return { type: 'finished', text: 'Pen.' };
            return { type: 'finished', text: 'Encerrado' };
        }
        if (code === 31) return { type: 'halftime', text: 'Intervalo' };
        if (type === 'notstarted') return { type: 'scheduled', text: '' };
        if (type === 'postponed') return { type: 'postponed', text: 'Adiado' };
        if (type === 'canceled') return { type: 'cancelled', text: 'Cancelado' };

        return { type: 'scheduled', text: desc || '' };
    },
};

/* =====================================================
   LOCAL STORAGE - Manual Games Management
   ===================================================== */
const GamesDB = {
    STORAGE_KEY: 'pdb_games',

    getAll() {
        const data = localStorage.getItem(this.STORAGE_KEY);
        return data ? JSON.parse(data) : [];
    },

    save(games) {
        localStorage.setItem(this.STORAGE_KEY, JSON.stringify(games));
    },

    add(game) {
        const games = this.getAll();
        game.id = Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
        game.createdAt = new Date().toISOString();
        games.push(game);
        this.save(games);
        return game;
    },

    update(id, updates) {
        const games = this.getAll();
        const index = games.findIndex(g => g.id === id);
        if (index > -1) {
            games[index] = { ...games[index], ...updates };
            this.save(games);
            return games[index];
        }
        return null;
    },

    delete(id) {
        const games = this.getAll();
        this.save(games.filter(g => g.id !== id));
    },

    getById(id) {
        return this.getAll().find(g => g.id === id);
    },
};
